blog/blog/urls.py
# -*- coding: utf-8 -*-
"""blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.conf.urls import include
# from django.contrib import admin
import sys
sys.path.append('..')
from friend import urls as friend_urls
from category import urls as category_urls
from article import urls as article_urls
from comment import urls as comment_urls
from account import urls as account_urls
from main import urls as main_urls


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^category',include(category_urls)),
    url(r'^friend',include(friend_urls)),
    url(r'^article',include(article_urls)),
    url(r'^comment',include(comment_urls)),
    url(r'^account',include(account_urls)),
    url(r'',include(main_urls)),
]

blog/category/urls.py
from django.conf.urls import url
from category import views
urlpatterns=[
    url(r'category_list',views.category_list),
    url(r'category_edit',views.category_edit),
    url(r'category_add',views.category_add),
    url(r'category_dele',views.category_delete),
    url(r'category_login',views.category_login),
    url(r'category_logout',views.category_logout),
    url(r'',views.category_list)
]

blog/category/models.py
from django.db import models

# Create your models here.

blog/database/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
# 用户信息数据库
class Account(models.Model):
    id=models.AutoField(primary_key=True) #用户id
    name=models.CharField(max_length=128,unique=True,null=False,db_index=True) #用户名
    password=models.CharField(max_length=256,null=False) #用户密码
    gender=models.CharField(max_length=16,default='unknown') #性别
    email=models.CharField(max_length=64,unique=True) #邮箱
    hobby=models.CharField(max_length=256,default=None) #邮箱
    description=models.CharField(max_length=512,default=None) #邮箱
    regis_date=models.DateTimeField(auto_now_add=True) #注册日期
    modify_date=models.DateTimeField(auto_now=True) #最后更新日期
    blog_num=models.SmallIntegerField(default=0) #发表博客数
    friend=models.ManyToManyField(to="Account") #关联好友

    # def __str__(self):
    #     return '姓名:{},邮箱:{},爱好:{},博客数量:{}'.format(self.name,self.email,self.hobby,self.blog_num)

# 分类/标签数据库
class Category(models.Model):
    id=models.AutoField(primary_key=True) #分类id
    name=models.CharField(max_length=128,null=True,db_index=True) #标签名称
    orderNo=models.IntegerField(default=1) #标签顺序
    description=models.CharField(max_length=128,null=True) #标签描述
    account = models.ForeignKey(to="Account",null=True)  # 标签作者


# 文章数据库
class Article(models.Model):
    id=models.AutoField(primary_key=True) #文章id
    title=models.CharField(max_length=128,null=False,db_index=True) #标题
    summary=models.CharField(max_length=512,default=None,db_index=True) #摘要
    text=models.TextField(max_length=9999999999,default=None) #文章内容
    read_num=models.SmallIntegerField(default=0) #阅读次数
    comment_num=models.SmallIntegerField(default=0) #评论数
    like_num=models.SmallIntegerField(default=0) #喜欢数 点赞数
    dislike_num=models.SmallIntegerField(default=0) #不喜欢数 吐槽数

    create_date=models.DateTimeField(auto_now_add=True) #创建日期
    modify_date=models.DateTimeField(auto_now=True) #修改日期

    account=models.ForeignKey(to="Account") #文章作者
    category=models.ManyToManyField(to="Category") #文章分类

# 评论数据库
class Comment(models.Model):
    id = models.AutoField(primary_key=True)  # 评论id
    comment_type=models.SmallIntegerField(default=1) #评论类型 1：文本 2：like 3：dislike
    comment_text=models.CharField(max_length=512,default=None,db_index=True) #评论内容
    comment_date=models.DateTimeField(auto_now_add=True) #评论日期事件
    retry=models.ForeignKey(to='Comment',null=True) #该评论关联的评论
    article=models.ForeignKey(to="Article",null=True) #评论对应的文章id
    account=models.ForeignKey(to="Account",null=True) #评论对应的账户id

blog/category/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render,redirect,HttpResponse

# import sys
# sys.path.append('..')

# Create your views here.

from database import models
from functools import wraps
from public_function_blog import *


@login_check
def category_list(request):

    # 数据库查询
    uid=request.COOKIES.get('uid','')
    # print('uid',uid)
    category_objs = models.Category.objects.filter(account_id=uid).order_by("orderNo") #给侧边栏和网页主体用

    # print(category_objs)
    # print(request.path_info)


    # 分页处理
    category_objs_show=models.Category.objects.filter(account_id=uid).exclude(name__in=['草稿','无标签文章','所有文章'])
    if category_objs_show:
        page_html,category_objs_slice=page_html_create(request,category_objs_show,10,10)
    else:
        page_html=''
        category_objs_slice=category_objs

    # 获取分组对应文章数量
    artical_counts = article_counts_category(request)

    return render(request,"category/category_list.html",{"category_objs":category_objs,
                                                         "category_objs_slice": category_objs_slice,
                                                         "request":request,
                                                         'artical_counts':artical_counts,
                                                         'page_html': page_html
                                                         })
@login_check
def category_edit(request):
    uid=request.COOKIES.get('uid','')
    category_objs = models.Category.objects.filter(account_id=uid).order_by("orderNo") #给侧边栏和网页主体用

    if request.method=='GET':
        # 获取分组对应文章数量
        artical_counts = article_counts_category(request)

        category_edit_id=request.GET.get('category_id')
        category_edit_obj=models.Category.objects.get(account_id=uid,id=category_edit_id)
        return render(request,'category/category_edit.html',{ "category_objs":category_objs,
                                                              "category_edit_obj":category_edit_obj,
                                                              'request':request,
                                                              'artical_counts': artical_counts,
                                                            })
    if request.method=='POST':
        category_edit_id=request.POST.get('category_id')
        category_edit_obj = models.Category.objects.get(account_id=uid, id=category_edit_id)
        new_category_name=request.POST.get('category_name')

        flag = False
        if new_category_name == '草稿' and models.Category.objects.filter(account_id=uid, name='草稿').exists():
            flag = True
        elif new_category_name == '无标签文章' and models.Category.objects.filter(account_id=uid, name='无标签文章').exists():
            flag = True
        elif new_category_name == '所有文章' and models.Category.objects.filter(account_id=uid, name='所有文章').exists():
            flag = True

        if flag:
            errorstr='标签名称不可用'
            # 获取分组对应文章数量
            artical_counts = article_counts_category(request)
            return render(request, 'category/category_edit.html', {"category_objs": category_objs,
                                                                   "category_edit_obj": category_edit_obj,
                                                                   'request': request,
                                                                   "errorstr":errorstr,
                                                                   'artical_counts': artical_counts,
                                                                   })
        new_category_description=request.POST.get('category_description')
        new_category_orderNo=request.POST.get('category_orderNo')

        if new_category_name == '草稿':
            big_category=models.Category.objects.filter(account_id=uid).order_by('id').reverse().first()
            if big_category.id<999:
                new_category_orderNo = 999
            else:
                new_category_orderNo = big_category.id+1
        elif new_category_name in ['无标签文章', '所有文章']:
            new_category_orderNo = 0

        # print(new_category_name,new_category_description,new_category_orderNo)

        category_obj = models.Category.objects.get(id=category_edit_id,account_id=uid)
        category_obj.name=new_category_name
        category_obj.description=new_category_description
        category_obj.orderNo=new_category_orderNo
        # print(category_obj, category_obj.name, category_obj.description, category_obj.orderNo)
        category_obj.save()
        return redirect('/category/category_list/')

@login_check
def category_add(request):
    uid = request.COOKIES.get('uid', '')
    category_objs = models.Category.objects.filter(account_id=uid)

    # 获取分组对应文章数量
    artical_counts = article_counts_category(request)
    # print(category_objs)
    if request.method=='GET':
        return render(request,'category/category_add.html',{"category_objs":category_objs,
                                                            'request': request,
                                                            'artical_counts': artical_counts,
                                                            })
    if request.method == 'POST':
        add_category_name=request.POST.get('category_name')
        add_category_description=request.POST.get('category_description')
        add_category_orderNo=request.POST.get('category_orderNo')

        flag=False
        if add_category_name=='草稿' and models.Category.objects.filter(account_id=uid,name='草稿').exists():
            flag=True
        elif add_category_name=='无标签文章' and models.Category.objects.filter(account_id=uid,name='无标签文章').exists():
            flag = True
        elif add_category_name == '所有文章' and models.Category.objects.filter(account_id=uid, name='所有文章').exists():
            flag = True

        if flag:
            errorstr='标签名称不可用'
            return render(request,'category/category_add.html',{"category_objs":category_objs,
                                                                'request': request,
                                                                "errorstr": errorstr,
                                                                'artical_counts': artical_counts,
                                                                })
        if  add_category_name=='草稿':
            add_category_orderNo=999
        elif add_category_name in ['无标签文章','所有文章']:
            add_category_orderNo = 0

        category_obj=models.Category(name=add_category_name,
                                     description=add_category_description,
                                     orderNo=add_category_orderNo
                                     )
        category_obj.account_id=uid
        models.Category.objects.bulk_create([category_obj], 1)
        return redirect('/category/category_list/')

@login_check
def category_delete(request):
    uid = request.COOKIES.get('uid', '')
    dele_id=request.GET.get("category_id")
    category_obj = models.Category.objects.get(id=dele_id,account_id=uid)
    category_obj.delete()
    return redirect('/category/category_list/')



def category_login(request):
    res=redirect('/category/')
    res.set_cookie('uid',195,max_age=365*24*3600)
    res.set_cookie('uname',"K931",max_age=365*24*3600)
    res.set_cookie('isLogin',True,max_age=365*24*3600)
    return res

def category_logout(request):
    res=redirect('/category/')
    res.delete_cookie('uid')
    res.delete_cookie('uname')
    res.delete_cookie('isLogin')
    return res

blog/templates/category/category_add.html
{# <!DOCTYPE html> #}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
    <title>Title</title>
    {% include 'base/head.html' %}
</head>
<body>

<div style="overflow: auto;width: 1000px;clear: both;margin: 0 auto;">
    {% include 'base/private_top.html'  %}
    <div style="position: relative;">
        {% include 'base/private_cebianlan.html' %}

        <form action="/category/category_add" method="post" enctype="multipart/form-data" style="position: absolute;left: 210px;">

            <div class="form-group">
                <input type="hidden" name="category_id" value="{{ category_edit_obj.id }}">

                <label for="exampleInputEmail1">请输入新的标签名称</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="category_name" placeholder="标签名称">
                <p style="color: red">{{ errorstr }}</p>
                <label for="exampleInputName1">请输入新的标签编号</label>
                <input type="number" class="form-control" id="exampleInputName1" name="category_orderNo" placeholder="标签编号" >

                <label for="exampleInputDescription1">请输入新的标签描述</label>
                <input type="text" class="form-control" id="exampleInputDescription1"  name="category_description" placeholder="标签描述">

            </div>
            <div>
                <p>
                    <input class="btn btn-warning" type="submit" value="确认修改">
    {#                <button class="btn btn-info" type="button"><a href="/category/category_list" style="color: white">放弃修改</a></button>#}
                </p>
            </div>

        </form>

    </div>
    {% include 'base/foot.html'  %}
    </div>

</body>
</html>

blog/templates/category/category_edit.html
{# <!DOCTYPE html> #}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
     <title>Title</title>
    {% include 'base/head.html' %}
</head>
<body>
<div style="overflow: auto;width: 1000px;clear: both;margin: 0 auto;">
    {% include 'base/private_top.html'  %}
    <div style="position: relative;">
    {% include 'base/private_cebianlan.html' %}

    <form action="/category/category_edit" method="post" enctype="multipart/form-data" style="position: absolute;left: 210px;">
        <div class="form-group">
            <input type="hidden" name="category_id" value="{{ category_edit_obj.id }}">

            <label for="exampleInputEmail1">请输入新的标签名称</label>
            <input type="text" class="form-control" id="exampleInputEmail1" name="category_name" value={{ category_edit_obj.name }}>
            <p style="color: red">{{ errorstr }}</p>
            <label for="exampleInputName1">请输入新的标签编号</label>
            <input type="number" class="form-control" id="exampleInputName1" name="category_orderNo" value={{ category_edit_obj.orderNo }}>

            <label for="exampleInputDescription1">请输入新的标签描述</label>
            <input type="text" class="form-control" id="exampleInputDescription1"  name="category_description" value={{ category_edit_obj.description }}>

        </div>
        <div>
            <p>
                <input class="btn btn-warning" type="submit" value="确认修改">
                <button class="btn btn-info" type="button"><a href="/category/category_list" style="color: white">放弃修改</a></button>
            </p>
        </div>
    </form>
    </div>

    {% include 'base/foot.html'  %}
    </div>
</body>
</html>

blog/templates/category/category_list.html
{# <!DOCTYPE html> #}
<meta http-equiv='Content-type' content='text/htm'>
<html lang="en">
<head>
     <title>Title</title>
    {% include 'base/head.html' %}
</head>
<body>
<div style="overflow: auto;width: 1000px;clear: both;margin: 0 auto;">
{% include 'base/private_top.html'  %}

<div style="position: relative;overflow:hidden;">
    {% include 'base/private_cebianlan.html' %}
    <div  style="position: absolute;left: 210px;">
    {#  单页查询结果  #}
    <table class="table table-hover" style="width:750px;">
        <thead>
            <tr>
                <td align="center">序号</td>
                <td align="center">博客分类</td>
                <td align="center">博客数</td>
                <td align="center">标签描述</td>
                <td style="text-align: center;">管理</td>
            </tr>
        </thead>
        <tbody>

        {% with count=1 %}


            {% for category in category_objs_slice %}
                {% if category.name not in '草稿,无标签文章,所有文章' %}
                    <tr>
                        <td align="center">{{forloop.counter}}</td>
                        <td align="center">{{category.name}}</td>
                        <td align="center">{{category.article_set.count}}</td>
                        <td align="center">{{category.description}}</td>
                        <td align="center">
                        <button type="button" class="btn btn-warning"><a href="/category/category_edit?category_id={{ category.id }}" style="color: white;">修改</a></button>
                        <button type="button" class="btn btn-danger"> <a href="/category/category_dele?category_id={{ category.id }}" style="color: white;">删除</button>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endwith %}
        </tbody>
    </table>

    {#  分页  #}
    {{ page_html|safe }}

    </div>
</div>

{% include 'base/foot.html'  %}

</div>
</body>
</html>